name: Flutter CI

on:
    pull_request: 
#   push:
#     branches:
#       - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Code Scanning
        uses: github/codeql-action@v2
        with:
          languages: dart

      - name: Lint Check
        run: flutter analyze

      - name: Build Flutter App
        run: flutter build apk
